### ISSUE TITLE
PFSense 2.4.4 Potential Issues

### ISSUE THREAD

**Issue by samypr100** [ndejong/pfsense_fauxapi#37]
Recently upgraded PFSense to 2.4.4 and started getting the following exception using faux v1.3.3:

```shell
Fatal error: Uncaught Error: Call to undefined function fauxapi\v1\split() in /etc/inc/fauxapi/fauxapi_auth.inc:48
Stack trace: #0 /etc/inc/fauxapi/fauxapi.inc(131): fauxapi\v1\fauxApiAuth->is_authenticated() 
#1 /etc/inc/fauxapi/fauxapi.inc(63): fauxapi\v1\fauxApi->__check_user_action_call(Object(fauxapi\v1\fauxApiActions), 'config_get', Array, '')
#2 /usr/local/www/fauxapi/v1/index.php(32): fauxapi\v1\fauxApi->__call('config_get', Array)
#3 {main} thrown in /etc/inc/fauxapi/fauxapi_auth.inc on line 48 PHP ERROR: Type: 1, File: /etc/inc/fauxapi/fauxapi_auth.inc, Line: 48,
Message: Uncaught Error: Call to undefined function fauxapi\v1\split() in /etc/inc/fauxapi/fauxapi_auth.inc:48
Stack trace: #0 /etc/inc/fauxapi/fauxapi.inc(131): fauxapi\v1\fauxApiAuth->is_authenticated() 
#1 /etc/inc/fauxapi/fauxapi.inc(63): fauxapi\v1\fauxApi->__check_user_action_call(Object(fauxapi\v1\fauxApiActions), 'config_get', Array, '')
#2 /usr/local/www/fauxapi/v1/index.php(32): fauxapi\v1\fauxApi->__call('config_get', Array)
#3 {main} thrown
```

**Comment by ndejong** [comment]
Hi @samypr100 - yes this was picked up and corrected yesterday in https://github.com/ndejong/pfsense_fauxapi/pull/35 - the issue is the use of a legacy PHP function `split()` - new FauxAPI package coming shortly

**Comment by samypr100** [comment]
Sorry, I didn't see an issue and decided to create one. I had not noticed an MR already fixed it. 👍

**Comment by ndejong** [comment]
I appreciate the report all the same - new package release v1.3_4 resolves this
